name: tremors
channels:
  - conda-forge
  - nvidia
dependencies:
  - python>=3.11
  - ollama
  - numpy
  - pandas
  - scipy
  - matplotlib
  - obspy
  - cartopy
  - requests
  - rich
  - pip
  - pip:
    - langchain
    - langchain-core
    - langgraph
    - langchain-openai
    - ipykernel
    - hatchling
    - pyarrow
    - -e .
